# Your personal GitHub token
github_token: <paste-your-token-here>
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens/new?scopes=repo&description=LongLog%20composer%20token

# Guest OS timezone
timezone: Europe/Moscow

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: longlog

# Virtual machine IP
ip: 192.168.10.130

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024
